version: '3.8'

services:
  wwebjs-api:
    build: https://github.com/Marcosarc/wwebjs-api.git  # Construir desde tu repo
    container_name: wwebjs_api
    restart: unless-stopped
    networks:
      - panelnet
    environment:
      - PORT=3000
      - SESSION_NAME=production_session
      - LOG_LEVEL=debug
      - API_KEY=tu_clave_secreta_generada  # ¡Obligatorio cambiar!
      - ENABLE_SWAGGER=true
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    volumes:
      - wwebjs-sessions:/app/sessions  # Ajusta según tu Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=panelnet"
      - "traefik.http.routers.wwebjs-api.rule=Host(`wwebjs2.srvapp2.site`)"
      - "traefik.http.routers.wwebjs-api.entrypoints=websecure"
      - "traefik.http.routers.wwebjs-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.wwebjs-api.loadbalancer.server.port=3000"

volumes:
  wwebjs-sessions:
    external: true

networks:
  panelnet:
    external: true
