version: '3.8'

services:
  app:
    container_name: wwebjs_api
    image: avoylenko/wwebjs-api:latest
    restart: always
    environment:
      - BASE_WEBHOOK_URL=https://wwebjs2.srvapp2.site
      - API_KEY=8a7dc96763ed02f4bd3f86cfd8a6ad68
      - MAX_ATTACHMENT_SIZE=5000000
      - SET_MESSAGES_AS_SEEN=TRUE
      - DISABLED_CALLBACKS=message_ack|message_reaction
      - ENABLE_SWAGGER_ENDPOINT=TRUE
    volumes:
      - wwebjs-sessions:/usr/src/app/sessions
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.wwebjs.rule=Host(`wwebjs2.srvapp2.site`)
        - traefik.http.routers.wwebjs.entrypoints=websecure
        - traefik.http.routers.wwebjs.tls.certresolver=letsencryptresolver
        - traefik.http.services.wwebjs.loadbalancer.server.port=3000
    networks:
      - panelnet

volumes:
  wwebjs-sessions:
    external: true

networks:
  panelnet:
    external: true
